package io.appkitchen.ante.core.designsystem.hct

import kotlin.math.abs
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin port to the Java it was ported from.
 *
 * `hct_fixtures.csv` was generated by running the upstream `HctSolver.solveToInt` (see NOTICE.md
 * for the commit) over every hue at the avatar chroma and tones, plus a coarser sweep of the rest
 * of the space including the chroma-0 and tone-0/100 shortcuts. A transcription slip anywhere in
 * the four ported files shows up here as a wrong ARGB rather than as a subtly off avatar.
 */
class HctSolverTest {

    @Test
    fun solveToInt_matchesUpstreamJavaFixtures() {
        val cases = fixtures()
        assertTrue("fixture file should not be empty", cases.size > 1000)
        for (case in cases) {
            val actual = HctSolver.solveToInt(case.hue, case.chroma, case.tone)
            assertEquals(
                "hue=${case.hue} chroma=${case.chroma} tone=${case.tone}",
                case.argb.toString(16),
                actual.toString(16),
            )
        }
    }

    /**
     * The property the design rule leans on: HCT tone is L*, so asking for a tone gets that tone
     * back. The solver's own contract is "sufficiently close" - within half an L* step is what the
     * upstream implementation delivers and what makes the contrast arithmetic in the spec hold.
     */
    @Test
    fun solveToInt_returnsRequestedTone() {
        for (case in fixtures()) {
            if (case.tone <= 0.0 || case.tone >= 100.0) continue
            val actualTone = ColorUtils.lstarFromArgb(case.argb)
            assertTrue(
                "hue=${case.hue} chroma=${case.chroma} asked tone ${case.tone}, got $actualTone",
                abs(actualTone - case.tone) < 0.5,
            )
        }
    }

    private data class Fixture(val hue: Double, val chroma: Double, val tone: Double, val argb: Int)

    private fun fixtures(): List<Fixture> {
        val text =
            HctSolverTest::class.java.getResourceAsStream("/hct_fixtures.csv")?.use {
                it.readBytes().decodeToString()
            } ?: error("hct_fixtures.csv missing from test resources")
        return text
            .lineSequence()
            .drop(1)
            .filter { it.isNotBlank() }
            .map { line ->
                val (h, c, t, argb) = line.split(',')
                Fixture(h.toDouble(), c.toDouble(), t.toDouble(), argb.toLong(16).toInt())
            }
            .toList()
    }
}
